# Generated by Django 5.2.7 on 2025-11-21 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Chunk of text from knowledge base')),
                ('source', models.CharField(help_text='Source file or document', max_length=255)),
                ('embedding', models.JSONField(help_text='Vector embedding for similarity search')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('sources', models.JSONField(default=list, help_text='List of sources used for the response')),
                ('source_type', models.CharField(choices=[('kb', 'Knowledge Base'), ('llm', 'External LLM'), ('mixed', 'Mixed')], default='kb', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_phi_detected', models.BooleanField(default=False)),
                ('phi_anonymized', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
