# Generated by Django 5.2.7 on 2025-10-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('antibiotics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_antibiotic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antibiotics.antibiotic')),
            ],
        ),
    ]
