# Generated by Django 5.2.7 on 2025-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bacteria_type', models.CharField(choices=[('gram_positive', 'Gram Positive'), ('gram_negative', 'Gram Negative')], max_length=50)),
                ('gram_stain', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
