# Generated by Django 5.2.7 on 2025-10-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bacteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('bacteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacteria.bacteria')),
            ],
        ),
    ]
